config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :todos do
  collection do
  get'/:id'=>'todos#change',as: :change
  end
  end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up)  <<  :name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@todos=Todo.all
		if params[:time1].present?
			@todos=@todos.where( :time => "true")
		end
		if params[:time2].present?
			@todos=@todos.where(:time => "false")
		end
	
	end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	
	def show
		@todo=Todo.where(:time =>"false")
	end
	def create
		@todo=Todo.new(thing_params)
		@todo.update_attribute(:time,"false")
		if @todo.save
			redirect_to root_path
		else render.new
		end
	end
	def new
		@todo=Todo.new
	end

	def edit
		@todo=Todo.find(params[:id])
	end
	def update
		@todo=Todo.find(params[:id])
		if @todo.update(things_params)
			redirect_to root_path
		else
			render :edit
		end
	end
	def destroy
		@todo=Todo.find(params[:id])
		@todo.destroy
		redirect_to root_path
	end

	def change
		@todo = Todo.find(params[:id])
		if @todo.time ==="false"
			@todo.update_attribute(:time,"true")
		else 
			@todo.update_attribute(:time,"false")
		end
		redirect_to root_path
	end


	private
	def  thing_params
		params.require(:todo).permit(:thing)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<h2>待辦事項</h2>

<%=form_tag  todos_path,method:"post" do %>
<%=text_field_tag "todo[thing]"%>

<%=submit_tag"update"%>
<%end%>

<%= link_to "View All", root_path%>


<%= form_tag root_path,method: "get" do%>
<%=hidden_field_tag :time2 , "false"%>
<%= submit_tag "undo"%>
<%end%>

<%= form_tag root_path,method: "get" do%>
<%=hidden_field_tag :time1 , "true"%>
<%= submit_tag "finish"%>
<%end%>

<% @todos.each do|todo|%>
<%= todo.thing %>
<% if todo.time ==="true"%>
<%= 'finish'%>
<% else %>
<%= 'undo'%>
<% end %>



<%= link_to "Edit", edit_todo_path(todo) %>
<%= link_to "Delete", todo_path(todo),method:"delete" %>
<%= button_to "change status", change_todos_path(todo), method: "get"%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%if user_signed_in? %>
hello <%=current_user.name %>
<%= link_to "sign out", destroy_user_session_path, method: "delete" %>
<%else %>
<%= link_to "register", new_user_registration_path %>
<%= link_to "sign in", new_user_session_path %>
<%end%>
<%= yield %>

</body>
</html>

app/views/todos/edit.html.erb
<h2>edit </h2>
<%= form_for @todo do|f| %>
<div>
<%= f.text_field :thing%>
</div>
<%=f.submit %>
<%end%>

app/views/todos/index.html.erb
<% if submit_tag =="undo"%>
<h2>finish</h2>
<% @todos.each do|todo|%>

<%end %>
<% else %>
<h2>undo</h2>
<% @todos.each do|todo|%>
<%= todo.thing %>
<% end %>
<% end%>

app/views/todos/show.html.erb
<%= @todo.thing %>